--[[ "This file was generated by Fennel. Do not modify." ]]
local theme = {}
theme["Normal"] = {bg = "#121212", fg = "#bd976a"}
theme["Identifier"] = {link = "Normal"}
theme["Variable"] = {link = "Identifier"}
theme["@variable"] = {link = "Variable"}
theme["@lsp.type.parameter"] = {link = "Identifier"}
theme["@lsp.type.property"] = {link = "Identifier"}
theme["@lsp.type.variable"] = {link = "Identifier"}
theme["@namespace"] = {link = "Identifier"}
theme["@parameter"] = {link = "Identifier"}
theme["@text.reference"] = {link = "Identifier"}
theme["Statement"] = {fg = "#4d9375"}
theme["Keyword"] = {fg = "#4d9375"}
theme["@keyword"] = {link = "Keyword"}
theme["Conditional"] = {link = "Statement"}
theme["Repeat"] = {link = "Statement"}
theme["Label"] = {link = "Statement"}
theme["Exception"] = {link = "Statement"}
theme["PreProc"] = {link = "Statement"}
theme["Include"] = {link = "Statement"}
theme["Define"] = {link = "Statement"}
theme["Macro"] = {link = "Statement"}
theme["PreCondit"] = {link = "Statement"}
theme["@preproc"] = {link = "Preproc"}
theme["Function"] = {fg = "#80a665"}
theme["@function"] = {link = "Function"}
theme["@method"] = {link = "Function"}
theme["@function.builtin"] = {link = "Function"}
theme["@lsp.type.decorator"] = {link = "Function"}
theme["@lsp.type.function"] = {link = "Function"}
theme["@lsp.type.method"] = {link = "Function"}
theme["Type"] = {fg = "#5da994"}
theme["Structure"] = {link = "Type"}
theme["StorageClass"] = {link = "Type"}
theme["Typedef"] = {link = "Type"}
theme["@type"] = {link = "Type"}
theme["@lsp.type.type"] = {link = "Type"}
theme["String"] = {fg = "#c98a7d"}
theme["@string"] = {link = "String"}
theme["Number"] = {fg = "#5da994"}
theme["@number"] = {link = "Number"}
theme["Float"] = {link = "Number"}
theme["Boolean"] = {fg = "#4d9375"}
theme["@boolean"] = {link = "Boolean"}
theme["Field"] = {fg = "#bd976a"}
theme["@field"] = {link = "Field"}
theme["@property"] = {link = "Field"}
theme["Constant"] = {fg = "#c98a7d"}
theme["Character"] = {link = "Constant"}
theme["@lsp.type.enumMember"] = {link = "Constant"}
theme["vimHiAttrib"] = {link = "Constant"}
theme["Comment"] = {fg = "#758575"}
theme["@comment"] = {link = "Comment"}
theme["@html.comment"] = {link = "Comment"}
theme["@lsp.type.comment"] = {link = "Comment"}
theme["@text.literal"] = {link = "Comment"}
theme["CtrlPLinePre"] = {link = "Comment"}
theme["LspCodeLens"] = {link = "Comment"}
theme["Operator"] = {fg = "#cb7676"}
theme["Delimiter"] = {fg = "#666666"}
theme["NvimParenthesis"] = {link = "Delimiter"}
theme["@punctuation"] = {link = "Delimiter"}
theme["DelimiterLight"] = {fg = "#666666"}
theme["@punctuation.bracket"] = {link = "DelimiterLight"}
theme["Special"] = {fg = "#cb7676"}
theme["Debug"] = {link = "Special"}
theme["SpecialChar"] = {link = "Special"}
theme["SpecialComment"] = {link = "Special"}
theme["Tag"] = {link = "Special"}
theme["@constant.builtin"] = {link = "Special"}
theme["@constructor"] = {link = "Special"}
theme["@punctuation.special"] = {link = "Special"}
theme["NonText"] = {fg = "#7a7a7a"}
theme["EndOfBuffer"] = {link = "NonText"}
theme["Whitespace"] = {link = "NonText"}
theme["Visual"] = {bg = "#333333"}
theme["Cursor"] = {bg = "#dbd7ca", fg = "#181818"}
theme["CursorColumn"] = {bg = "#181818"}
theme["CursorLine"] = {link = "CursorColumn"}
theme["LineNr"] = {fg = "#7a7a7a"}
theme["LineNrAbove"] = {fg = "#7a7a7a"}
theme["LineNrBelow"] = {link = "LineNrAbove"}
theme["CursorLineNr"] = {fg = "#bfbaaa"}
theme["TermCursor"] = {reverse = true}
theme["Search"] = {bg = "#4d9375", fg = "#181818"}
theme["CurSearch"] = {link = "Search"}
theme["QuickFixLine"] = {link = "Search"}
theme["Substitute"] = {link = "Search"}
theme["IncSearch"] = {bg = "#d4976c", fg = "#181818"}
theme["Error"] = {bg = "#cb7676", fg = "#dbd7ca"}
theme["ErrorMsg"] = {fg = "#cb7676"}
theme["WarningMsg"] = {fg = "#d4976c"}
theme["MoreMsg"] = {bold = true, fg = "#4d9375"}
theme["ModeMsg"] = {bold = true, fg = "#80a665"}
theme["Question"] = {fg = "#4d9375"}
theme["Bold"] = {bold = true}
theme["Italic"] = {italic = true}
theme["Underlined"] = {fg = "#80a665", underline = true}
theme["@text.underline"] = {link = "Underlined"}
theme["@text.uri"] = {link = "Underlined"}
theme["Title"] = {bold = true, fg = "#d4976c"}
theme["@text.title"] = {link = "Title"}
theme["ColorColumn"] = {bg = "#181818"}
theme["MatchParen"] = {bg = "#2a2a2a", fg = "#dbd7ca"}
theme["Folded"] = {fg = "#d4976c"}
theme["Ignore"] = {fg = "#7a7a7a"}
theme["Conceal"] = {link = "Ignore"}
theme["SpecialKey"] = {link = "Normal"}
theme["NvimSpacing"] = {link = "Normal"}
theme["DiffText"] = {link = "Visual"}
theme["DiffAdd"] = {bg = "#4d9375", fg = "#181818"}
theme["@text.diff.add"] = {link = "DiffAdd"}
theme["Added"] = {fg = "#4d9375"}
theme["DiffAdded"] = {link = "Added"}
theme["@diff.plus"] = {link = "Added"}
theme["DiffChange"] = {bg = "#d4976c", fg = "#181818"}
theme["@text.diff.change"] = {link = "DiffChange"}
theme["Changed"] = {fg = "#d4976c"}
theme["DiffChanged"] = {link = "Changed"}
theme["@diff.delta"] = {link = "Changed"}
theme["DiffDelete"] = {bg = "#cb7676", fg = "#181818"}
theme["@text.diff.delete"] = {link = "DiffDelete"}
theme["Removed"] = {fg = "#cb7676"}
theme["DiffRemoved"] = {link = "Removed"}
theme["@diff.minus"] = {link = "Removed"}
theme["NormalFloat"] = {link = "Normal"}
theme["FloatBorder"] = {fg = "#80a665"}
theme["FloatTitle"] = {bold = true, fg = "#4d9375"}
theme["Pmenu"] = {link = "Normal"}
theme["PmenuExtra"] = {link = "Pmenu"}
theme["PmenuKind"] = {link = "Pmenu"}
theme["PmenuSbar"] = {fg = "#7a7a7a"}
theme["PmenuThumb"] = {bg = "#dbd7ca", fg = "#dbd7ca"}
theme["PmenuSel"] = {bg = "#80a665", fg = "#181818"}
theme["PmenuExtraSel"] = {link = "PmenuSel"}
theme["PmenuKindSel"] = {link = "PmenuSel"}
theme["StatusLine"] = {bg = "#121212", bold = true, fg = "#dbd7ca"}
theme["MsgSeparator"] = {link = "StatusLine"}
theme["StatusLineNC"] = {bg = "#121212", bold = true, fg = "#959da5"}
theme["TabLine"] = {bg = "#121212", fg = "#959da5"}
theme["TabLineFill"] = {bg = "#121212", fg = "#c98a7d"}
theme["TabLineSel"] = {bg = "#80a665", bold = true, fg = "#121212"}
theme["TabLineSelSep"] = {bg = "#121212", bold = true, fg = "#80a665"}
theme["TabLineSep"] = {bg = "#121212", fg = "#121212"}
theme["Directory"] = {link = "Type"}
theme["netrwExe"] = {link = "Changed"}
theme["netrwClassify"] = {link = "Comment"}
theme["SpellBad"] = {fg = "#d4976c", sp = "#dbd7ca"}
theme["SpellCap"] = {fg = "#4d9375", sp = "#dbd7ca"}
theme["SpellLocal"] = {fg = "#d4976c", sp = "#dbd7ca"}
theme["SpellRare"] = {fg = "#cb7676", sp = "#dbd7ca"}
theme["helpSectionDelim"] = {link = "Comment"}
theme["helpHyperTextEntry"] = {link = "Statement"}
theme["helpExample"] = {link = "String"}
theme["helpHeadline"] = {link = "Title"}
theme["helpHyperTextJump"] = {link = "Underlined"}
theme["helpURL"] = {link = "Underlined"}
theme["DiagnosticDeprecated"] = {sp = "#d4976c", strikethrough = true}
theme["DiagnosticError"] = {fg = "#cb7676"}
theme["DiagnosticErrorFloating"] = {link = "DiagnosticError"}
theme["DiagnosticSignError"] = {link = "DiagnosticError"}
theme["DiagnosticVirtualTextError"] = {link = "DiagnosticError"}
theme["DiagnosticUnderlineError"] = {underline = true}
theme["DiagnosticWarn"] = {fg = "#d4976c"}
theme["DiagnosticFloatingWarn"] = {link = "DiagnosticWarn"}
theme["DiagnosticSignWarn"] = {link = "DiagnosticWarn"}
theme["DiagnosticVirtualTextWarn"] = {link = "DiagnosticWarn"}
theme["DiagnosticUnderlineWarn"] = {underline = true}
theme["DiagnosticHint"] = {fg = "#4d9375"}
theme["DiagnosticFloatingHint"] = {link = "DiagnosticHint"}
theme["DiagnosticSignHint"] = {link = "DiagnosticHint"}
theme["DiagnosticVirtualTextHint"] = {link = "DiagnosticHint"}
theme["DiagnosticUnderlineHint"] = {underline = true}
theme["DiagnosticInfo"] = {fg = "#6394bf"}
theme["DiagnosticFloatingInfo"] = {link = "DiagnosticInfo"}
theme["DiagnosticSignInfo"] = {link = "DiagnosticInfo"}
theme["DiagnosticVirtualTextInfo"] = {link = "DiagnosticInfo"}
theme["DiagnosticUnderlineInfo"] = {underline = true}
theme["DiagnosticOk"] = {fg = "#4d9375"}
theme["DiagnosticFloatingOk"] = {link = "DiagnosticOk"}
theme["DiagnosticSignOk"] = {link = "DiagnosticOk"}
theme["DiagnosticVirtualTextOk"] = {link = "DiagnosticOk"}
theme["Todo"] = {bg = "#dbd7ca", fg = "#121212"}
theme["@text.todo"] = {link = "Todo"}
theme["htmlLink"] = {link = "Underlined"}
theme["markdownBold"] = {link = "Bold"}
theme["markdownItalic"] = {link = "Italic"}
theme["@markup.heading"] = {link = "Special"}
theme["@markup.raw.block.markdown"] = {link = "Special"}
theme["@markup.list"] = {link = "Operator"}
theme["@markup.link"] = {fg = "#80a665", underline = true}
theme["@punctuation.special.markdown"] = {link = "Comment"}
theme["@property.lua"] = {link = "Normal"}
theme["LazyNormal"] = {link = "Normal"}
theme["LazyButtonActive"] = {bg = "#80a665", fg = "#181818"}
theme["LazyH1"] = {fg = "#80a665"}
theme["LazyH2"] = {fg = "#80a665"}
theme["LazySpecial"] = {fg = "#6394bf"}
theme["MasonHeaderSecondary"] = {link = "LazyButtonActive"}
theme["MasonHighlightBlock"] = {link = "LazyButtonActive"}
theme["FzfLuaNormal"] = {link = "Normal"}
theme["FzfLuaTitle"] = {link = "FloatTitle"}
theme["FzfLuaBorder"] = {link = "FloatBorder"}
theme["FzfLuaCursor"] = {link = "Cursor"}
theme["FzfLuaCursorLine"] = {link = "CursorLine"}
theme["FzfLuaCursorLineNr"] = {link = "CursorLineNr"}
theme["FzfLuaSearch"] = {link = "IncSearch"}
theme["FzfLuaScrollFloatEmpty"] = {link = "PmenuSbar"}
theme["FzfLuaScrollFloatFull"] = {link = "PmenuThumb"}
theme["MiniTablineCurrent"] = {link = "TabLineSel"}
theme["MiniTablineHidden"] = {link = "Normal"}
theme["MiniTablineVisible"] = {link = "MiniTablineHidden"}
theme["MiniTablineModifiedCurrent"] = {bg = "#4d9375", bold = true, fg = "#121212"}
theme["MiniTablineModifiedHidden"] = {link = "TabLineFill"}
theme["MiniTablineModifiedVisible"] = {link = "MiniTablineModifiedHidden"}
theme["MiniTablineTabpageSection"] = {link = "IncSearch"}
theme["MiniJump2dSpot"] = {link = "TabLineSel"}
theme["IblIndent"] = {fg = "#333333"}
theme["GitSignsAdd"] = {link = "Added"}
theme["GitSignsChange"] = {link = "Changed"}
theme["GitSignsDelete"] = {link = "Removed"}
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.g.colors_name = "vitesse"
vim.o.background = "dark"
for group, attr in pairs(theme) do
  vim.api.nvim_set_hl(0, group, attr)
end
return nil
